### ISSUE TITLE
An option to "Do Nothing"

### ISSUE THREAD

**Issue by cas--** [cas--/autoshutdown#1]
From: Pluto Crat plutocrat@gmail.com 

On the Plugin preferences / configuration page it would be useful to have an option to "Do Nothing". Currently you can do this by going into the Plugins page and disabling the plugin there, but a "Do Nothing" option would be more convenient.

**Comment by Maxzilla60** [comment]
I have an issue where disabling the plugin doesn't even stop the shutdown event and it's often confusing whether or not it will do a shutdown.

Having an option like this would be a reassuring addition.
