### ISSUE TITLE
Hybernate and Suspend are greyed out

### ISSUE THREAD

**Issue by PierBover** [cas--/autoshutdown#3]
The only available option is to shutdown.

I'm on Ubuntu 15.04 and Deluge 1.13.11

**Comment by PierBover** [comment]
Ah it seems that the options are greyed out if the system has auto suspend enabled. This confused me... maybe a little message to the user would be great.

**Comment by PierBover** [comment]
Well I was wrong, I have disabled auto suspend in the system and the options are still greyed out...

**Comment by cas--** [comment]
Fixed: 3bc1cd130412d469
